name: D2Parser Tests

on:
  push:
    paths:
      - *
  create:
  pull_request:
    paths:
      - *
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-pytho@v2
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: python -m pip install -r requirements.txt
      - run: npm i -g pnpm
      - run: cd TS
      - run: pnpm install
      - run: pnpm test
